# Generated by Django 5.1.5 on 2025-03-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ambiente_curso_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='sala',
            new_name='ambiente',
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='periodo',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noturno'), ('S', 'Sabado')], default='M', max_length=50),
        ),
    ]
